"""Generate reviewable HA files without connecting to HA or handling credentials."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
import sysconfig
from urllib.parse import urlsplit


REPORTS = {
    "battery": "Battery report",
    "solar": "Solar power report",
    "solar_today": "Solar today report",
    "status": "Energy status report",
    "alarms": "Energy alarms report",
}
SCRIPT_IDS = {key: f"igw_google_{key}" for key in REPORTS}
SCRIPT_IDS["alarms"] = "igw_announce_alarms"
BLUEPRINT_RELATIVE_PATH = Path("blueprints/script/igw/announce_energy.yaml")


def validate_entity(value: str, domain: str) -> str:
    """Reject incomplete examples and YAML/template injection before rendering."""
    if not re.fullmatch(rf"{domain}\.[a-z0-9_]+", value):
        raise ValueError(f"Use an existing {domain} entity ID from Home Assistant.")
    object_id = value.split(".", 1)[1]
    if object_id in {"example", "placeholder", "your_nest", "your_tts"} or any(
        object_id.startswith(prefix) for prefix in ("your_", "replace_", "placeholder_")
    ):
        raise ValueError(f"Replace the example {domain} entity with a real entity ID.")
    return value


def validate_url(value: str) -> str:
    """Accept only a fixed HTTPS endpoint with no embedded secrets or template."""
    try:
        parsed = urlsplit(value)
        parsed.port
        hostname = parsed.hostname or ""
    except ValueError as exc:
        raise ValueError("Use a valid HTTPS IGW URL ending in /v1/energy.") from exc
    if (
        parsed.scheme != "https"
        or not hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
        or parsed.path != "/v1/energy"
        or re.search(r"[\s{}<>\\]", value)
        or any(part in hostname.lower() for part in ("replace", "your_host", "placeholder"))
        or hostname.lower() in {"example.com", "example.net", "example.org"}
        or hostname.lower().endswith((".example.com", ".example.net", ".example.org", ".invalid"))
    ):
        raise ValueError("Use your real HTTPS IGW URL ending in /v1/energy, without credentials or a query.")
    return value


def blueprint_source() -> Path:
    candidates = (
        Path(__file__).resolve().parent.parent / BLUEPRINT_RELATIVE_PATH,
        Path(sysconfig.get_path("data")) / "share/igw-google-voice" / BLUEPRINT_RELATIVE_PATH,
    )
    for path in candidates:
        if path.is_file():
            return path
    raise ValueError("Blueprint asset is missing; use a complete checkout or reinstall the package.")


def render_package(tts_entity: str, media_player: str, cloudflare_access: bool, max_age: int) -> str:
    validate_entity(tts_entity, "tts")
    validate_entity(media_player, "media_player")
    if isinstance(max_age, bool) or not 5 <= max_age <= 300:
        raise ValueError("Maximum response age must be between 5 and 300 seconds.")
    lines = [
        "# Generated by igw-google-voice. Credentials stay in secrets.yaml.",
        "# HA REST command DEBUG logging includes authentication headers.",
        "logger:",
        "  logs:",
        "    homeassistant.components.rest_command: warning",
        "",
        "rest_command:",
        "  igw_energy_report:",
        "    url: !secret igw_energy_url",
        "    method: GET",
        "    timeout: 10",
        "    verify_ssl: true",
        "    headers:",
        "      Authorization: !secret igw_energy_authorization",
        '      Accept: "application/json"',
        '      User-Agent: "IGWEnergyVoice/1.0 (+https://github.com/victron-venus/inverter-gateway)"',
        '      Cache-Control: "no-cache, no-store"',
    ]
    if cloudflare_access:
        lines.extend([
            "      CF-Access-Client-Id: !secret igw_cf_access_client_id",
            "      CF-Access-Client-Secret: !secret igw_cf_access_client_secret",
        ])
    lines.extend([
        "",
        "script:",
        "  igw_google_energy_dispatch:",
        '    alias: "IGW energy dispatcher (private)"',
        "    use_blueprint:",
        "      path: igw/announce_energy.yaml",
        "      input:",
        f"        tts_entity: {json.dumps(tts_entity)}",
        f"        media_player: {json.dumps(media_player)}",
        f"        max_response_age: {max_age}",
    ])
    for key, name in REPORTS.items():
        lines.extend([
            "",
            f"  {SCRIPT_IDS[key]}:",
            f"    alias: {json.dumps(name)}",
            '    icon: "mdi:account-voice"',
            "    mode: queued",
            "    max: 10",
            "    trace:",
            "      stored_traces: 0",
            "    sequence:",
            "      - action: script.igw_google_energy_dispatch",
            "        data:",
            f"          report_key: {key}",
        ])
    return "\n".join(lines) + "\n"


def render_files(*, igw_url: str, tts_entity: str, media_player: str,
                 cloudflare_access: bool = False, max_age: int = 30) -> dict[Path, str]:
    validate_url(igw_url)
    package = render_package(tts_entity, media_player, cloudflare_access, max_age)
    secrets = (
        "# Merge into HA secrets.yaml, which must remain outside version control.\n"
        "# This is an example, not a usable credential file.\n"
        f"igw_energy_url: {json.dumps(igw_url)}\n"
        'igw_energy_authorization: "Bearer REPLACE_WITH_SCOPED_READ_TOKEN"\n'
    )
    if cloudflare_access:
        secrets += (
            'igw_cf_access_client_id: "REPLACE_WITH_CF_ACCESS_CLIENT_ID"\n'
            'igw_cf_access_client_secret: "REPLACE_WITH_CF_ACCESS_CLIENT_SECRET"\n'
        )
    return {
        Path("packages/igw_google_voice.yaml"): package,
        BLUEPRINT_RELATIVE_PATH: blueprint_source().read_text(),
        Path("igw.secrets.example.yaml"): secrets,
        Path("INSTALL.md"): (
            "# Install the rendered adapter\n\n"
            "The renderer has not contacted Home Assistant or verified entity existence.\n"
            "Confirm the selected TTS provider and Cast speaker in HA first.\n\n"
            "1. Copy blueprints/ and packages/ into the HA configuration directory.\n"
            "2. Merge igw.secrets.example.yaml keys into the existing HA secrets.yaml,\n"
            "   replacing every credential placeholder. Restrict that file to its owner.\n"
            "   Never copy the example into packages/.\n"
            "3. Enable homeassistant: packages: !include_dir_named packages in\n"
            "   configuration.yaml, merging with any existing homeassistant settings.\n"
            "4. Run HA configuration validation, then restart HA to load rest_command.\n"
            "5. Call script.igw_google_{battery,solar,solar_today,status} and\n"
            "   script.igw_announce_alarms in HA.\n"
            "6. Expose only those five wrapper scripts to Google Assistant and assign\n"
            "   their room. Keep script.igw_google_energy_dispatch private.\n\n"
            "See the repository README and docs/routines.md for validation and Google setup.\n"
        ),
    }


def write_files(output: Path, files: dict[Path, str]) -> None:
    """Refuse collisions and symlinks inside the chosen staging directory."""
    if output.is_symlink():
        raise ValueError("Output paths must not contain symbolic links.")
    # Resolve system aliases such as macOS /var -> /private/var outside our output.
    output = output.parent.resolve() / output.name
    for relative in files:
        destination = output / relative
        parent = destination
        while parent != output.parent:
            if parent.is_symlink():
                raise ValueError("Output paths must not contain symbolic links.")
            parent = parent.parent
        if destination.exists():
            raise ValueError("Output already contains generated files; use a new output directory.")
    output.mkdir(parents=True, exist_ok=True, mode=0o700)
    for relative, text in files.items():
        destination = output / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("x", encoding="utf-8") as handle:
            handle.write(text)
        if relative.name.endswith("secrets.example.yaml"):
            destination.chmod(0o600)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    render = subparsers.add_parser("render-config", help="Render an HA package and blueprint for review.")
    render.add_argument("--igw-url", required=True, help="Real HTTPS URL ending in /v1/energy; no credentials.")
    render.add_argument("--tts-entity", required=True, help="Existing HA tts entity ID.")
    render.add_argument("--media-player", required=True, help="Existing HA Google Cast media_player entity ID.")
    render.add_argument("--cloudflare-access", action="store_true", help="Require CF Access service-token secrets too.")
    render.add_argument("--max-response-age", type=int, default=30)
    render.add_argument("--output", type=Path, required=True, help="New staging directory; never an active HA config directory.")
    args = parser.parse_args(argv)
    try:
        files = render_files(
            igw_url=args.igw_url, tts_entity=args.tts_entity, media_player=args.media_player,
            cloudflare_access=args.cloudflare_access, max_age=args.max_response_age,
        )
        write_files(args.output, files)
    except (ValueError, OSError) as exc:
        # Validation messages never interpolate inputs, URLs, credentials, or file contents.
        message = str(exc) if isinstance(exc, ValueError) else "Could not write output files; check the destination and permissions."
        parser.exit(2, f"Configuration error: {message}\n")
    print("Rendered five report scripts, shared blueprint, and a credential example. Read INSTALL.md before installation.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
