"""Render an optional HA voice trigger for the independent local Cast service."""

from __future__ import annotations

import argparse
import ipaddress
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit

from .__main__ import REPORTS, SCRIPT_IDS, write_files


PACKAGE_PATH = Path("packages/igw_google_voice.yaml")
SECRETS_PATH = Path("igw.cast.secrets.example.yaml")
_PRIVATE_NETWORKS = tuple(ipaddress.ip_network(value) for value in (
    "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16",
))
_ALLOWED_REPORTS = "['battery', 'solar', 'solar_today', 'status', 'alarms']"
_VALID_REPORT = f"report_key is defined and report_key is string and report_key in {_ALLOWED_REPORTS}"


def validate_service_url(value: str) -> str:
    """Accept only an HTTP origin on a literal, canonical RFC1918 IPv4 address."""
    message = "Use an HTTP origin with a private IPv4 address, optional port, and no path or credentials."
    if not isinstance(value, str) or re.search(r"[\s{}<>\\]", value):
        raise ValueError(message)
    try:
        parsed = urlsplit(value)
        address = ipaddress.IPv4Address(parsed.hostname or "")
        port = parsed.port
    except ValueError as exc:
        raise ValueError(message) from exc
    if (
        parsed.scheme != "http"
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path
        or parsed.query
        or parsed.fragment
        or "?" in value
        or "#" in value
        or not any(address in network for network in _PRIVATE_NETWORKS)
        or port is not None and not 1 <= port <= 65535
    ):
        raise ValueError(message)
    origin = f"http://{address}" + (f":{port}" if port is not None else "")
    if value != origin:
        raise ValueError(message)
    return origin


def render_cast_trigger_files(service_url: str) -> dict[Path, str]:
    """Return a replacement HA package without contacting services or reading secrets."""
    service_url = validate_service_url(service_url)
    safe_key = "{{ report_key if " + _VALID_REPORT + " else 'invalid' }}"
    endpoint = service_url + "/v1/reports/" + safe_key
    lines = [
        "# Generated by igw-cast-ha. Replace the previous package; do not install both.",
        "# HA only triggers playback. The local Cast service fetches and renders IGW data.",
        "# Keep credentials in secrets.yaml and REST command logging at warning or above.",
        "logger:",
        "  logs:",
        "    homeassistant.components.rest_command: warning",
        "",
        "rest_command:",
        "  igw_cast_report:",
        f"    url: {json.dumps(endpoint)}",
        "    method: POST",
        "    timeout: 10",
        "    headers:",
        "      Authorization: !secret igw_cast_authorization",
        '      Accept: "application/json"',
        '      Cache-Control: "no-store"',
        "",
        "script:",
        "  igw_google_energy_dispatch:",
        '    alias: "IGW energy dispatcher (private)"',
        "    mode: queued",
        "    max: 10",
        "    max_exceeded: warning",
        "    trace:",
        "      stored_traces: 0",
        "    fields:",
        "      report_key:",
        "        name: Report",
        "        required: true",
        "        selector:",
        "          select:",
        f"            options: {_ALLOWED_REPORTS}",
        "    sequence:",
        "      - if:",
        "          - condition: template",
        "            value_template: >-",
        "              {{ not (" + _VALID_REPORT + ") }}",
        "        then:",
        '          - stop: "Invalid energy report."',
        "            error: true",
        "      - variables:",
        "          cast_response: {}",
        "      - action: rest_command.igw_cast_report",
        "        data:",
        '          report_key: "{{ report_key }}"',
        "        response_variable: cast_response",
        "        continue_on_error: true",
        "      - choose:",
        '          - conditions: "{{ cast_response is mapping and cast_response.get(\'status\') == 202 }}"',
        "            sequence:",
        '              - stop: "Energy report accepted by the display service."',
        '          - conditions: "{{ cast_response is mapping and cast_response.get(\'status\') == 409 }}"',
        "            sequence:",
        '              - stop: "An energy report is already being prepared or played."',
        "        default:",
        '          - stop: "The energy display service could not accept the report."',
        "            error: true",
    ]
    for key, name in REPORTS.items():
        lines.extend([
            "",
            f"  {SCRIPT_IDS[key]}:",
            f"    alias: {json.dumps(name)}",
            '    icon: "mdi:account-voice"',
            "    mode: queued",
            "    max: 10",
            "    trace:",
            "      stored_traces: 0",
            "    sequence:",
            "      - action: script.igw_google_energy_dispatch",
            "        data:",
            f"          report_key: {key}",
        ])
    return {
        PACKAGE_PATH: "\n".join(lines) + "\n",
        SECRETS_PATH: (
            "# Merge this key into HA secrets.yaml outside version control.\n"
            "# This token authorizes playback on the local Cast service only.\n"
            'igw_cast_authorization: "Bearer REPLACE_WITH_LOCAL_CAST_API_TOKEN"\n'
        ),
        Path("INSTALL.md"): (
            "# Install the optional HA voice trigger\n\n"
            "The Cast service fetches IGW reports, creates offline speech and video, and\n"
            "plays them on its configured Nest. HA only submits a playback request.\n"
            "HA needs no IGW token, TTS provider, blueprint, or Cast integration for this trigger.\n"
            "A working HA-to-Google account link is still required for voice activation.\n\n"
            "1. Verify the standalone Cast service works and is reachable from HA on\n"
            "   the chosen trusted LAN address. This HTTP route carries a local playback\n"
            "   token; keep it on the trusted LAN and do not expose it through a public tunnel.\n"
            "2. Back up the existing HA configuration. Replace exactly\n"
            "   packages/igw_google_voice.yaml with the generated package. Do not add a\n"
            "   second package with the same scripts. This renderer and the original\n"
            "   TTS adapter are alternative configurations, not packages to combine.\n"
            "3. Merge igw.cast.secrets.example.yaml into HA's existing secrets.yaml,\n"
            "   replacing the placeholder with the Cast service API token. Keep the real\n"
            "   file outside Git with owner-only permissions. Do not put it in packages/.\n"
            "4. Enable homeassistant: packages: !include_dir_named packages if needed;\n"
            "   merge with the existing homeassistant settings. Preserve the generated\n"
            "   REST warning log level; DEBUG logging can expose authentication headers.\n"
            "5. Run HA configuration validation, then restart HA to load the REST command.\n"
            "   The old energy REST command or blueprint may remain installed but is\n"
            "   unused by this package. Remove old IGW/TTS secrets only if nothing else uses them.\n"
            "6. Call script.igw_google_status in HA and verify the selected Nest plays\n"
            "   a report. HTTP 202 means accepted, not proof of successful later playback.\n"
            "   HTTP 409 means busy; it does not queue another Cast report. Other failures\n"
            "   stop the HA script with a generic error. Check the Cast service for playback errors.\n"
            "7. Preserve the existing Google exposure and room assignment of the five\n"
            "   report scripts. Their entity IDs and names are unchanged. Keep\n"
            "   script.igw_google_energy_dispatch private. A new installation must\n"
            "   link Google, expose the five report scripts, and sync devices first.\n\n"
            "Say: Hey Google, activate Energy status report. The fixed output Nest is\n"
            "configured in the Cast service, regardless of which microphone hears you.\n"
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--service-url", required=True, help="Trusted-LAN HTTP origin using a private IPv4 address.")
    parser.add_argument("--output", required=True, type=Path, help="New staging directory, not the active HA config.")
    args = parser.parse_args(argv)
    try:
        write_files(args.output, render_cast_trigger_files(args.service_url))
    except (ValueError, OSError) as exc:
        message = str(exc) if isinstance(exc, ValueError) else "Could not write the generated files."
        parser.exit(2, f"Configuration error: {message}\n")
    print("Rendered five HA report triggers and a local-token example. Read INSTALL.md before replacing the package.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
